import uuid

### General testing data ###
TEST_API_DASHBOARD_ID = "cd0a2fa0-bae3-e34b-165c-d78f65353b58"

### General user data ###
TEST_TENANT_ID = "44796316-f1ac-427a-8ab9-257aed02a531"
TEST_USER_ID = "32d3161b-f419-4571-8fa4-931fa972f4a8"

### Cases ####
TEST_CASE_NAME_1 = "Test Case using Automation Script"
TEST_CASE_NAME_2 = "Test Case using Automation Script 1"
TEST_CASE_NAME_UPDATED = "Test Case using Automation Script - Updated"
TEST_CASE_DESCRIPTION = "Verifies that a case is created successfully via automation script."
TEST_CASE_DESCRIPTION_UPDATED = "Verifies that a case is updated successfully via automation script."
TEST_INVALID_CASE_ID = str(uuid.uuid4())
TEST_CASE_STATUS_OPEN = "OPEN"
TEST_CASE_STATUS_IN_PROGRESS = "INPROGRESS"
TEST_CASE_CONTENT_STATUS_NEW = "NEW"
TEST_CASE_CONTENT_STATUS_ESCALED = "ESCALATED"
TEST_CASE_RISK_RATING_ADHERANCE = "Adherence"
TEST_CASE_RISK_RATING_INFORMATION = "Info"

### Folders ###
TEST_FOLDER_NAME = "Test Folder using Automation Script"
TEST_FOLDER_NAME_UPDATED = "Test Folder using Automation Script - Updated"
TEST_FOLDER_DESCRIPTION = "Verifies that a folder is created successfully via automation script."
TEST_FOLDER_DESCRIPTION_UPDATED = "Verifies that a folder is updated successfully via automation script."
TEST_FOLDER_INVALID_ID = str(uuid.uuid4())

### Reports ###
TEST_REPORT_ID = str(uuid.uuid4())
TEST_REPORT_TITLE = "Test Report using Automation Script"
TEST_REPORT_CASE_COMPLIANCE_RATE_KPI = "CaseComplianceRate"
TEST_REPORT_OVERALL_COMPLIANCE_RATE_KPI = "OverallComplianceRate"
TEST_REPORT_OVERALL_ESCALATION_RATE_KPI = "OverallEscalationRate"
TEST_REPORT_OVERALL_RESOLUTION_TIME_KPI = "OverallResolutionTime"
TEST_REPORT_CASE_ESCALATION_RATE_KPI = "CaseEscalationRate"
TEST_REPORT_CASE_RESOLUTION_TIME_KPI = "CaseResolutionTime"
TEST_REPORT_TOTAL_NUMBER_KPI = "CT"
TEST_REPORT_RECORDED_CALLS_TO_TOTAL_KPI = "CTA"
TEST_REPORT_PENDING_ARCHIVE_KPI = "Unarchived"
TEST_REPORT_CURRENT_CALLS_KPI = "CC"
TEST_REPORT_AUDIT_LOGS_KPI = "AU"

### Records ###
TEST_RECORD_ID = "88f4a6a0-9907-4751-9091-75012f5aa662"
TEST_RECORD_INVALID_ID = str(uuid.uuid4())
TEST_RECORD_EXPORT_ZIP_ID = "12345678"
TEST_RECORD_EXPORT_ZIP_NAME = "recordExport"
TEST_RECORD_TOPIC_NAME = "96137643 - Eminescu, 6007 ..."
TEST_DEFAULT_RECORDS_PATH = "https://stage-teams.asc-recording.app/"
# For share record #
TEST_RECORD_EXPIRTION_DATE = "2027-05-06"
TEST_RECORD_START_TIME = "1777901618939"
TEST_RECORD_END_TIME = "1777901653939"
TEST_RECORD_DURATION = "00:00:35"

### Users ###
TEST_USER_06_DEV2_ID = "6a5c667b-dd17-4853-b72a-806af00dc1dd" # FOR CREATE : this is user_id
TEST_USER_06_DEV2_NAME = "TestUser06 Dev2ASC" # FOR CREATE
TEST_USER_06_DEV2_EMAIL = "test06@dev2.asc.d"

### Rules ###
### Recording rules ###
TEST_RECORDING_RULE_ZQA_BULK_ID = "1fa79b57-4eef-4378-ba5f-61685c104187"
### REPLAY rules ###
TEST_REPLAY_RULE_EQA_REPLAY_ALL_ID = "8f517806-6979-4590-fdcc-f91933e32029"
### ACCESS rules ###
TEST_ACCESS_RULE_ADMINISTRATOR_ID = "1c7cbc97-2c36-4f58-b4e0-c25218e98a47"
### ANALYTICS rules ###
TEST_ANALYTICS_RULE_ANALYZE_ALL_ID = "589e8c3e-d4d0-482d-8ef1-f4e74ba1abac"
### STORAGE rules ###
TEST_STORAGE_RULE_ID = "fd26075e-b641-4b32-8269-0e4b03fda776"

### Licences ###
TEST_COMPLIANCE_VOICE_RECORDING_POLICY_LICENE_ID = "6"
TEST_COMPLIANCE_UC_RECORDING_LICENCE_ID = "1"
TEST_SMART_VOICE_RECORDING_POLICY_ID = "8"
TEST_SMART_UC_RECORDING_POLICY_ID = "3"
TEST_ENTRY_VOICE_RECORDING_POLICY_ID = "13"
TEST_SMART_BASE_LICENCE_ID = "11"
TEST_COMPLIANCE_BASE_LICENCE_ID = "12"
TEST_CHAT_RECORDING_STANDALONE_LICENCE_ID = "5"
TEST_RECORDING_INSIGHTS_AI_LICENCE_ID = "10"
TEST_COMPLIANCE_VOICE_RECORDING_AND_ANALYTICS_LICENCE_ID = "7"
TEST_COMPLIANCE_UC_RECORDING_AND_ANALYTICS_LICENCE_ID = "2"
TEST_SMART_VOICE_AND_ANALYTICS_LICENCE_ID = "9"
TEST_SMART_UC_RECORDING_AND_ANALYTICS_LICENCE_ID = "4"